hassanhabib/RESTFulSense

RESTFulSense.Tests/Controllers/RESTFulControllerTests.cs
RESTFulSense/Controllers/IRESTFulController.cs
RESTFulSense/Controllers/RESTFulController.cs
RESTFulSense/Models/BadGatewayObjectResult.cs
RESTFulSense/Models/ExpectationFailedObjectResult.cs
RESTFulSense/Models/FailedDependencyObjectResult.cs
RESTFulSense/Models/GatewayTimeoutObjectResult.cs
RESTFulSense/Models/GoneObjectResult.cs
RESTFulSense/Models/HttpVersionNotSupportedObjectResult.cs
RESTFulSense/Models/InsufficientStorageObjectResult.cs
RESTFulSense/Models/InternalServerErrorObjectResult.cs
RESTFulSense/Models/LockedObjectResult.cs
RESTFulSense/RESTFulSense.csproj

This PR implements the RESTFulController to offer the following methods:
BadGateway
ExpectationFailed
FailedDependency
GatewayTimeout
Gone
HttpVersionNotSupported
InsufficientStorage
InternalServerError
Locked

RESTFulController Code Support

---

RESTFulSense.Tests/Services/ValidationServiceTests.cs
RESTFulSense/Models/Exceptions/HttpResponseUrlNotFoundException.cs
RESTFulSense/Services/ValidationService.cs

We want to capture a Url Not Found Exception versus an Entity Not Found Exception

Not Found Url Exception

---

RESTFulSense/Controllers/RESTFulController.cs

Same like MVC ControllerBase https://github.com/dotnet/aspnetcore/blob/master/src/Mvc/Mvc.Core/src/ControllerBase.cs

Add [NonAction] Attribute to Controller Methods

---

readme.md

Spelling is obvious and capitalization correction is for keeping the overall consistency of document.

A few spelling and capitalization corrections.

---

RESTFulSense/Clients/IRESTFulApiClient.cs
RESTFulSense/Clients/IRESTFulApiFactoryClient.cs
RESTFulSense/Clients/RESTFulApiClient.cs
RESTFulSense/Clients/RESTFulApiFactoryClient.cs

CLIENT: Support Cancellation Tokens for RESTFulSense Clients & Client Factory

---

RESTFulSense.WebAssembly/Clients/IRESTFulApiClient.cs
RESTFulSense.WebAssembly/Clients/IRESTFulApiFactoryClient.cs
RESTFulSense.WebAssembly/Clients/RESTFulApiClient.cs
RESTFulSense.WebAssembly/Clients/RESTFulApiFactoryClient.cs
RESTFulSense/Clients/IRESTFulApiClient.cs
RESTFulSense/Clients/IRESTFulApiFactoryClient.cs
RESTFulSense/Clients/RESTFulApiClient.cs
RESTFulSense/Clients/RESTFulApiFactoryClient.cs

resolves named ticket reference from title.

EXPOSURE: Support No Return 204 Scenario #37

---

RESTFulSense/Clients/RESTFulApiClient.cs
RESTFulSense/Clients/RESTFulApiFactoryClient.cs

Updated RESTFulApiClient and RESTFulApiFactoryClient to post text/plain content without JSON serialization.

MEDIUM FIX: Support text/plain 

---

RESTFulSense/Clients/RESTFulApiClient.Conversions.cs
RESTFulSense/Clients/RESTFulApiClient.cs
RESTFulSense/Clients/RESTFulApiFactoryClient.Conversions.cs
RESTFulSense/Clients/RESTFulApiFactoryClient.cs

Changes:
- Added a new Conversions partial class to handle media type conversions
- Supports application/octet-stream

MEDIUM FIX: Support application/octet-stream content types

---

RESTFulSense.WebAssembly/Clients/RESTFulApiClient.Conversions.cs
RESTFulSense.WebAssembly/Clients/RESTFulApiClient.cs
RESTFulSense.WebAssembly/Clients/RESTFulApiFactoryClient.Conversions.cs
RESTFulSense.WebAssembly/Clients/RESTFulApiFactoryClient.cs
RESTFulSense.WebAssembly/RESTFulSense.WebAssembly.csproj
RESTFulSense/Clients/RESTFulApiClient.cs

MEDIUM FIX: Support `application-json`

---

readme.md

CODE RUB: Update Readme

---

readme.md

DOCUMENTATIONS: Cleanup Readme HTML Tags

---

readme.md

@hassanhabib Revised please review and merge.

DOCUMENTATIONS: Readme Badge Uniformity

---

RESTFulSense.WebAssembly/Clients/IRESTFulApiClient.cs
RESTFulSense.WebAssembly/Clients/IRESTFulApiFactoryClient.cs
RESTFulSense.WebAssembly/Clients/RESTFulApiClient.cs
RESTFulSense.WebAssembly/Clients/RESTFulApiFactoryClient.cs

CLIENTS: Get Stream Content

---

RESTFulSense/Clients/IRESTFulApiClient.cs
RESTFulSense/Clients/IRESTFulApiFactoryClient.cs
RESTFulSense/Clients/RESTFulApiClient.Conversions.NewtonSoft.cs
RESTFulSense/Clients/RESTFulApiClient.Conversions.cs
RESTFulSense/Clients/RESTFulApiClient.cs
RESTFulSense/Clients/RESTFulApiFactoryClient.Conversions.NewtonSoft.cs
RESTFulSense/Clients/RESTFulApiFactoryClient.Conversions.cs
RESTFulSense/Clients/RESTFulApiFactoryClient.cs

CLIENTS: Add custom serialization and deserialization func

---

readme.md

DOCUMENTATIONS: Documentation update with custom serialization support

---

RESTFulSense.WebAssembly/RESTFulSense.WebAssembly.csproj
RESTFulSense/RESTFulSense.csproj

RELEASE: 2.18.1

---

RESTFulSense.WebAssembly/RESTFulSense.WebAssembly.csproj
RESTFulSense/RESTFulSense.csproj

CONFIGS: Release 2.19.0

---

RESTFulSense/Controllers/RESTFulController.cs
RESTFulSense/RESTFulSense.csproj

CONTROLLERS: Gracefully Handle Data

CONTROLLERS: Gracefully Handle Mapping Data

---

RESTFulSense.Tests/Services/ValidationServiceTests.ProblemDetails.cs

CODE RUB: Resolves Build Error ValidationServiceTests

---

RESTFulSense.Tests/Models/Attributes/RESTFulRestrictHeaderAttributes/RESTFulRestrictHeaderAttributeTests.Logic.cs
RESTFulSense.Tests/Models/Attributes/RESTFulRestrictHeaderAttributes/RESTFulRestrictHeaderAttributeTests.cs
RESTFulSense/Models/Attributes/RESTFulRestrictHeaderAttribute.cs

DATA: RESTFul Restrict Header Attribute
